sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
install:
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc
  - npm install
script:
  - npm truffle test
before_script:
  - testrpc > /dev/null &
  - sleep 5
after_script:
  - npm run ./node_modules/.bin/solidity-coverage && cat coverage/lcov.info | coveralls
